services:
    PoP\Categories\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\Categories\TypeResolvers\:
        resource: '../src/TypeResolvers/*'
        public: true
